name: Lint

on:
  push:
    paths:
      - ".github/workflows/lint.yml"
      - "backend/.pylintrc"
      - "**.py"
  pull_request:

permissions:
  contents: read

jobs:
  pylint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry config virtualenvs.create false
          poetry install --no-root --no-interaction --no-ansi
      - name: Run pylint
        run: |
          pylint --rcfile=backend/.pylintrc $(git ls-files '*.py')
